### ISSUE TITLE
Consider renaming .destroy() and .retrieve() methods

### ISSUE THREAD

**Issue by alimony** [xalien10/pyfortnox#55]
I'd suggest the following method renames:

`.destroy()` --> `.delete()`
`.retrieve()` --> `.get()`

I think these method names would be more intuitive as they also match the HTTP methods used.

**Comment by xalien10** [comment]
Actually we don't want to use generics method names to be mixed up with service name.
Like we're calling create not post, so we think it is more relevant to use destroy and retrieve than delete and get

**Comment by alimony** [comment]
Fair enough.
